config/routes.rb
Rails.application.routes.draw do

  resources :u, only: [:index, :show] do
    scope module: :u do
      resources :articles, only: [:index, :show]
    end
  end

  get 'home' => 'home#show'
  namespace :home do

    resources :articles do
      member do
        post :publish
        post :draft
      end
    end
    resources :comments

    resource :withdrawals

    namespace :settings do
      resource :profiles
      resource :accounts
      resource :passwords
    end
  end

  devise_for :users,
      controllers: {
        registrations: 'registrations',
        # sessions: 'sessions'
      }

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  include AASM

  aasm do
    state :draft, :initial => true
    state :published

    event :publish, before: ->{ self.published_at = Time.now } do
      transitions :from => :draft, :to => :published
    end

    event :draft do
      transitions :from => :published, :to => :draft
    end
  end

  has_many :comments

  belongs_to :user

  validates :title, presence: true
  validates :body_source, presence: true

  def body_text
    RedcarpetCompiler.html_to_text(self.body)
  end
end

app/controllers/home/articles_controller.rb
class Home::ArticlesController < AuthorizedController

  include AddBreadcrumbs

  before_action :set_article, only: [:show, :edit, :update, :destroy, :publish, :draft]

  # GET /articles
  def index
    @articles = current_user.articles.all
  end

  # GET /articles/1
  def show
    add_breadcrumb @article.title
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    add_breadcrumb @article.title, [:home, @article]
    add_breadcrumb '編集'
  end

  # POST /articles
  def create
    @article = current_user.articles.build(article_params)
    @article.body = RedcarpetCompiler.compile(@article.body_source)

    if @article.valid?
      @article.save!
      case params[:ope][:cmd]
      when 'publish'
        @article.publish!
        flash[:success] = '記事を公開しました。'
      when 'save'
        flash[:success] = '記事を保存しました。'
      else
        raise
      end
      redirect_to [:home, @article]
    else
      render :new
    end
  end

  def publish
    @article.publish!
    flash[:success] = '記事を公開しました。'
    redirect_to [:home, @article]
  end

  def draft
    @article.draft!
    flash[:success] = '記事を下書きにしました。'
    redirect_to [:home, @article]
  end

  # PATCH/PUT /articles/1
  def update

    @article.assign_attributes(article_params)

    if @article.valid?
      @article.body = RedcarpetCompiler.compile(@article.body_source)
      @article.save!

      flash[:success] = '記事を更新しました。'
      redirect_to [:home, @article]
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy

    flash[:success] = '記事を削除しました。'
    redirect_to home_articles_url
  end

  private

    def set_article
      @article = current_user.articles.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body_source)
    end
end

app/controllers/home/comments_controller.rb
class Home::CommentsController < AuthorizedController

  def create
    @article = Article.published.find(params[:comment][:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/home/settings/accounts_controller.rb
class Home::Settings::AccountsController < Home::Settings::BaseController

  before_filter do
    add_breadcrumb('アカウント設定')
  end

  def edit
  end

  def update
    current_user.assign_attributes(user_params)

    if current_user.valid?
      current_user.save!
      flash[:success] = '保存しました'
      redirect_to action: :edit
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:screen_name, :email)
    end

end

app/controllers/home/settings/base_controller.rb
class Home::Settings::BaseController < AuthorizedController

  before_filter do
    add_breadcrumb_home
    add_breadcrumb('設定', edit_home_settings_profiles_path)
  end

end

app/controllers/home/settings/passwords_controller.rb
class Home::Settings::PasswordsController < Home::Settings::BaseController

  before_filter do
    add_breadcrumb('パスワード設定')
  end

  def edit
    @change_password = ChangePassword.new
  end

  def update
    @change_password = ChangePassword.new params[:change_password]
    @change_password.valid?

    unless current_user.valid_password?(@change_password.current_password)
      @change_password.errors.add(:current_password, 'が違います')
    end

    if @change_password.new_password != @change_password.new_password_confirmation
      @change_password.errors.add(:new_password_confirmation, 'が同じではありません')
    end

    render action: :edit and return if @change_password.errors.any?

    current_user.password = @change_password.new_password
    current_user.save!

    flash[:success] = '変更しました'
    redirect_to action: :edit
  end
end

app/controllers/home/settings/profiles_controller.rb
class Home::Settings::ProfilesController < Home::Settings::BaseController

  before_filter do
    add_breadcrumb('プロフィール設定')
  end

  def update
    current_user.assign_attributes(user_params)

    if current_user.valid?
      current_user.save!
      flash[:success] = '保存しました'
      redirect_to action: :edit
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:user_name, :user_description)
    end
end

app/controllers/home/withdrawals_controller.rb
class Home::WithdrawalsController < AuthorizedController

  def edit
  end

  def destroy
    current_user.destroy
    redirect_to root_path, notice: '退会しました'
  end
end

app/controllers/home_controller.rb
class HomeController < AuthorizedController

  def show
    @articles = current_user.articles
    @comments = current_user.comments.includes(:article => :user)
  end
end

app/controllers/u/articles_controller.rb
class U::ArticlesController < ApplicationController

  before_action :set_user, only: [:index, :show]
  before_action :set_article, only: [:show]

  # GET /articles
  def index
    @articles = @user.articles.published.includes(:user, {comments: :user}).all
  end

  # GET /articles/1
  def show
    @comment = Comment.new(article_id: @article.id)
  end

  private

    def set_user
      @user = User.where(screen_name: params[:u_id]).first
    end

    def set_article
      @article = Article.published.includes(:user, {comments: :user}).find(params[:id])
    end
end

app/views/home/articles/_form.html.haml
= bootstrap_form_for [:home, @article], layout: :horizontal do |f|

  = f.alert_message '以下の項目を修正して下さい。'

  = f.text_field :title, autofocus: true

  = f.text_area :body_source, rows: 20

  = f.static_control :aasm_state

  .form-group
    .col-sm-offset-2.col-sm-10

      = f.button @article.new_record? ? '下書き保存' : '変更する', name: 'ope[cmd]', value: 'save', class: 'btn btn-lg btn-default'

      - if @article.draft?
        = f.button '公開する', name: 'ope[cmd]', value: 'publish', class: 'btn btn-lg btn-default'

      .pull-right
        = link_to '削除する', [:home, @article], :method => :delete, :data => { :confirm => '本当によろしいですか?' }, class: 'btn btn-danger btn-lg'

app/views/home/articles/edit.html.haml
%h1 編集

= render 'form'

app/views/home/articles/index.html.haml
%h1 記事一覧

= link_to '+ 新しい記事を作成する', new_home_article_path, class: 'btn btn-primary btn-lg'

- @articles.each do |article|
  %h2
    = link_to article.title, edit_home_article_path(article)
  .well
    %div= raw article.body
    %div= article.aasm_state
  %hr

app/views/home/articles/new.html.haml
%h1 新規投稿

= render 'form'

app/views/home/articles/show.html.haml
%div
  .pull-right= link_to 'フロント側で確認', u_article_path(current_user.screen_name, @article.id)

%h1
  = @article.title

.well
  = raw @article.body

%div
  状態: #{@article.aasm_state}

%div
  公開日時: #{safe_date_localize @article.published_at}

%div{style: 'margin-top: 20px;'}
  = link_to '編集する', edit_home_article_path(@article), class: 'btn btn-default btn-lg'
  - if @article.draft?
    = link_to '公開する', publish_home_article_path, class: 'btn btn-default btn-lg', method: :post
  - elsif @article.published?
    = link_to '下書きにする', draft_home_article_path, class: 'btn btn-default btn-lg', method: :post

  .pull-right
    = link_to '削除する', [:home, @article], :method => :delete, :data => { :confirm => '本当によろしいですか?' }, class: 'btn btn-danger btn-lg'