config/routes.rb
Rails.application.routes.draw do

  resources :u, only: [:index, :show] do
    scope module: :u do
      resources :articles, only: [:index, :show]
    end
  end

  get 'home' => 'home#show'
  namespace :home do

    resources :articles do
      member do
        post :publish
        post :draft
      end
    end
    resources :comments

    resource :withdrawals

    namespace :settings do
      resource :profiles
      resource :accounts
      resource :passwords
    end
  end

  devise_for :users,
      controllers: {
        registrations: 'registrations',
        # sessions: 'sessions'
      }

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  include AASM

  aasm do
    state :draft, :initial => true
    state :published

    event :publish, before: ->{ self.published_at = Time.now } do
      transitions :from => :draft, :to => :published
    end

    event :draft do
      transitions :from => :published, :to => :draft
    end
  end

  has_many :comments

  belongs_to :user

  validates :title, presence: true
  validates :body_source, presence: true

  def body_text
    RedcarpetCompiler.html_to_text(self.body)
  end
end

app/controllers/home/articles_controller.rb
class Home::ArticlesController < AuthorizedController

  include AddBreadcrumbs

  before_action :set_article, only: [:show, :edit, :update, :destroy, :publish, :draft]

  # GET /articles
  def index
    @articles = current_user.articles.all
  end

  # GET /articles/1
  def show
    add_breadcrumb @article.title
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    add_breadcrumb @article.title, [:home, @article]
    add_breadcrumb '編集'
  end

  # POST /articles
  def create
    @article = current_user.articles.build(article_params)
    @article.body = RedcarpetCompiler.compile(@article.body_source)

    if @article.valid?
      @article.save!
      case params[:ope][:cmd]
      when 'publish'
        @article.publish!
        flash[:success] = '記事を公開しました。'
      when 'save'
        flash[:success] = '記事を保存しました。'
      else
        raise
      end
      redirect_to [:home, @article]
    else
      render :new
    end
  end

  def publish
    @article.publish!
    flash[:success] = '記事を公開しました。'
    redirect_to [:home, @article]
  end

  def draft
    @article.draft!
    flash[:success] = '記事を下書きにしました。'
    redirect_to [:home, @article]
  end

  # PATCH/PUT /articles/1
  def update

    @article.assign_attributes(article_params)

    if @article.valid?
      @article.body = RedcarpetCompiler.compile(@article.body_source)
      @article.save!

      flash[:success] = '記事を更新しました。'
      redirect_to [:home, @article]
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy

    flash[:success] = '記事を削除しました。'
    redirect_to home_articles_url
  end

  private

    def set_article
      @article = current_user.articles.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body_source)
    end
end

app/controllers/u/articles_controller.rb
class U::ArticlesController < ApplicationController

  before_action :set_user, only: [:index, :show]
  before_action :set_article, only: [:show]

  # GET /articles
  def index
    @articles = @user.articles.published.includes(:user, {comments: :user}).all
  end

  # GET /articles/1
  def show
    @comment = Comment.new(article_id: @article.id)
  end

  private

    def set_user
      @user = User.where(screen_name: params[:u_id]).first
    end

    def set_article
      @article = Article.published.includes(:user, {comments: :user}).find(params[:id])
    end
end

app/controllers/u_controller.rb
class UController < ApplicationController

  before_action :set_user, only: [:index, :show]

  private

    def set_user
      @user = User.includes(:articles).where(screen_name: params[:id]).first
    end
end

app/views/u/articles/_comments.html.haml
.js_comments
  - comments.each do |comment|
    %div{style: 'margin-bottom: 5px;'}
      = image_tag comment.user.gravatar_url(length: 30)
      = link_to comment.user.screen_name, u_path(comment.user.screen_name)
      .pull-right
        = l comment.created_at
    %div.well.well-sm
      = simple_format comment.body, wrapper_tag: ''

app/views/u/articles/index.html.haml
.page-header
  %h1
    #{@user.screen_name} さんの記事一覧

- @articles.each do |article|
  %div
    %h2= link_to article.title, u_article_path(article.user.screen_name, article)
    %div= truncate(article.body_text)

app/views/u/articles/show.html.haml
- if current_user == @article.user
  %div
    .pull-right
      = link_to '編集', edit_home_article_path(@article)

%h1
  = link_to @article.title, u_article_path(@article.user.screen_name, @article)

%div
  = raw @article.body

%div
  .pull-right
    = link_to u_path(@article.user.screen_name) do
      = image_tag @article.user.gravatar_url(length: 20)
      = @article.user.screen_name
    = l @article.published_at

.clearfix

%hr

= render partial: 'comments', locals: {comments: @article.comments.order(:created_at)}

- if current_user
  = render partial: 'home/comments/form', locals: {comment: @comment}