config/routes.rb
Rails.application.routes.draw do

  resources :u, only: [:index, :show] do
    scope module: :u do
      resources :articles, only: [:index, :show]
    end
  end

  get 'home' => 'home#show'
  namespace :home do

    resources :articles do
      member do
        post :publish
        post :draft
      end
    end
    resources :comments

    resource :withdrawals

    namespace :settings do
      resource :profiles
      resource :accounts
      resource :passwords
    end
  end

  devise_for :users,
      controllers: {
        registrations: 'registrations',
        # sessions: 'sessions'
      }

  root 'welcome#index'

end

app/controllers/home/articles_controller.rb
class Home::ArticlesController < AuthorizedController

  include AddBreadcrumbs

  before_action :set_article, only: [:show, :edit, :update, :destroy, :publish, :draft]

  # GET /articles
  def index
    @articles = current_user.articles.all
  end

  # GET /articles/1
  def show
    add_breadcrumb @article.title
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    add_breadcrumb @article.title, [:home, @article]
    add_breadcrumb '編集'
  end

  # POST /articles
  def create
    @article = current_user.articles.build(article_params)
    @article.body = RedcarpetCompiler.compile(@article.body_source)

    if @article.valid?
      @article.save!
      case params[:ope][:cmd]
      when 'publish'
        @article.publish!
        flash[:success] = '記事を公開しました。'
      when 'save'
        flash[:success] = '記事を保存しました。'
      else
        raise
      end
      redirect_to [:home, @article]
    else
      render :new
    end
  end

  def publish
    @article.publish!
    flash[:success] = '記事を公開しました。'
    redirect_to [:home, @article]
  end

  def draft
    @article.draft!
    flash[:success] = '記事を下書きにしました。'
    redirect_to [:home, @article]
  end

  # PATCH/PUT /articles/1
  def update

    @article.assign_attributes(article_params)

    if @article.valid?
      @article.body = RedcarpetCompiler.compile(@article.body_source)
      @article.save!

      flash[:success] = '記事を更新しました。'
      redirect_to [:home, @article]
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy

    flash[:success] = '記事を削除しました。'
    redirect_to home_articles_url
  end

  private

    def set_article
      @article = current_user.articles.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body_source)
    end
end

app/controllers/home/comments_controller.rb
class Home::CommentsController < AuthorizedController

  def create
    @article = Article.published.find(params[:comment][:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/home/settings/accounts_controller.rb
class Home::Settings::AccountsController < Home::Settings::BaseController

  before_filter do
    add_breadcrumb('アカウント設定')
  end

  def edit
  end

  def update
    current_user.assign_attributes(user_params)

    if current_user.valid?
      current_user.save!
      flash[:success] = '保存しました'
      redirect_to action: :edit
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:screen_name, :email)
    end

end

app/controllers/home/settings/base_controller.rb
class Home::Settings::BaseController < AuthorizedController

  before_filter do
    add_breadcrumb_home
    add_breadcrumb('設定', edit_home_settings_profiles_path)
  end

end

app/controllers/home/settings/passwords_controller.rb
class Home::Settings::PasswordsController < Home::Settings::BaseController

  before_filter do
    add_breadcrumb('パスワード設定')
  end

  def edit
    @change_password = ChangePassword.new
  end

  def update
    @change_password = ChangePassword.new params[:change_password]
    @change_password.valid?

    unless current_user.valid_password?(@change_password.current_password)
      @change_password.errors.add(:current_password, 'が違います')
    end

    if @change_password.new_password != @change_password.new_password_confirmation
      @change_password.errors.add(:new_password_confirmation, 'が同じではありません')
    end

    render action: :edit and return if @change_password.errors.any?

    current_user.password = @change_password.new_password
    current_user.save!

    flash[:success] = '変更しました'
    redirect_to action: :edit
  end
end

app/controllers/home/settings/profiles_controller.rb
class Home::Settings::ProfilesController < Home::Settings::BaseController

  before_filter do
    add_breadcrumb('プロフィール設定')
  end

  def update
    current_user.assign_attributes(user_params)

    if current_user.valid?
      current_user.save!
      flash[:success] = '保存しました'
      redirect_to action: :edit
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:user_name, :user_description)
    end
end

app/controllers/home/withdrawals_controller.rb
class Home::WithdrawalsController < AuthorizedController

  def edit
  end

  def destroy
    current_user.destroy
    redirect_to root_path, notice: '退会しました'
  end
end

app/controllers/home_controller.rb
class HomeController < AuthorizedController

  def show
    @articles = current_user.articles
    @comments = current_user.comments.includes(:article => :user)
  end
end

app/views/home/show.html.haml
.row
  .col-sm-9
    = link_to '+ 新しい記事を作成する', new_home_article_path, class: 'btn btn-primary btn-lg'

    %h3
      公開記事
      %span.badge{style: 'vertical-align: 5px'}= @articles.published.size

    - @articles.published.each do |article|
      .list-group
        = link_to edit_home_article_path(article), class: 'list-group-item' do
          %h3.list-group-item-heading
            = article.title
          %div.list-group-item-text
            = truncate(article.body_text)
          %div.list-group-item-text.pull-right
            [#{article.aasm_state}]
            = safe_date_localize article.published_at
          .clearfix

    %h3
      下書記事
      %span.badge{style: 'vertical-align: 5px'}= @articles.draft.size

    - @articles.draft.each do |article|
      .list-group
        = link_to edit_home_article_path(article), class: 'list-group-item' do
          %h3.list-group-item-heading
            = article.title
          %div.list-group-item-text
            = truncate(article.body_text)
          %div.list-group-item-text.pull-right
            [#{article.aasm_state}]
            = safe_date_localize article.published_at
          .clearfix

    %h3
      コメント
      %span.badge{style: 'vertical-align: 5px'}= current_user.comments.size

    - @comments.each do |comment|
      .list-group
        = link_to u_article_path(comment.article.user, comment.article), class: 'list-group-item' do
          %h3.list-group-item-heading
            = comment.body
          %div.list-group-item-text
            .pull-left
              = comment.article.title
            .pull-right
              = safe_date_localize comment.created_at
            .clearfix

  .col-sm-3
    .thumbnail
      .text-center{style: 'height: 130px'}= image_tag current_user.gravatar_url
      .caption.text-center
        %p #{current_user.user_name} @#{current_user.screen_name}
        %p= current_user.user_description


    .col-xs-12{style: 'margin-bottom: 5px;'}= link_to 'プロフィール編集', edit_home_settings_profiles_path, class: 'btn btn-default btn-block'
    .col-xs-12= link_to 'アカウント編集', edit_home_settings_accounts_path, class: 'btn btn-default btn-block'